export const SET_USER = 'SET_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const USER_NOT_FOUND = 'USER_NOT_FOUND'
export const SET_DEVICE = 'SET_DEVICE'
export const SET_ORDERS = 'SET_ORDERS'
